# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC常用用法总结' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RAC常用用法总结
pod 'ReactiveCocoa', '~> 2.5'
pod 'AFNetworking'

end
